//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dir Name=&quot;Documents&quot; CreationTime=&quot;06/30/2018 20:44:03&quot; LastAccessTime=&quot;10/30/2018 19:27:10&quot; LastWriteTime=&quot;10/29/2018 14:52:54&quot; Attributes=&quot;ReadOnly, Directory&quot; Owner=&quot;VIACHESLAV\Viacheslav&quot; UserRights=&quot;Allow: FullControl, Modify, Synchronize, ReadAndExecute, Synchronize; Deny:&quot; Size=&quot;008393266708&quot;&gt;
        ///  &lt;dir Name=&quot;WindowsPowerShell&quot; CreationTime=&quot;09/25/2018 15:53:47&quot; LastAccessTime=&quot;10/28/2018 20:50:20&quot; LastWriteTime=&quot;10/25/2018 16:17:06&quot; Attributes=&quot;Directory&quot; Owner=&quot;BUILTIN\Administrators&quot; UserRights=&quot;Al [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLDocument {
            get {
                return ResourceManager.GetString("XMLDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;bigtext&gt;
        ///  When exchanging data between a browser and a server, the data can only be text.
        ///  ?&gt;
        ///  JSON is text, and we can convert any JavaScript object into JSON, and send JSON to the server.
        ///  &gt;
        ///  !--
        ///  We can also convert any JSON received from the server into JavaScript objects.
        ///
        ///  This way we can work with the data as JavaScript objects, with no complicated parsing and translations.
        ///&lt;/bigtext&gt;.
        /// </summary>
        internal static string XMLDocumentWithConstant {
            get {
                return ResourceManager.GetString("XMLDocumentWithConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;node&gt;
        ///  &lt;test attr1=&quot; 1--213 &quot; attr2  =  &quot;shgdv723yeqka,ds&quot;/&gt;
        ///  &lt;test attr1 =  &quot; 
        ///      hello
        ///      &quot;
        ///        attr2=&quot;&quot;
        ///&gt;Love&lt;/test&gt;
        ///&lt;/node&gt;.
        /// </summary>
        internal static string XMLDocumentWithTwoElements {
            get {
                return ResourceManager.GetString("XMLDocumentWithTwoElements", resourceCulture);
            }
        }
    }
}
